services:
  python:
    build: .
    tty: true
    ports:
      - "5000:8000"
    volumes:
      - .:/usr/app/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              count: 1
              capabilities: [gpu]